- name: "install ssl-cert"
  apt:
    name: ssl-cert

- name: "create {{ perun_certs_dir }} directory"
  file:
    path: "{{ perun_certs_dir }}"
    state: directory

- name: "use certbot certificates"
  when: perun_use_certbot_certificates
  block:
    - name: "create certbot cert for  {{ perun_rpc_hostname }}"
      include_role:
        name: cesnet.certbot_certs
        apply:
          tags: [ 'perun_certs' ]
      vars:
        certbot_hostname: "{{ perun_rpc_hostname }}"
        certbot_prehook: perun_prehook.sh
        certbot_posthook: perun_posthook.sh

    - name: "create certbot cert for  {{ perun_ngui_hostname }}"
      include_role:
        name: cesnet.certbot_certs
        apply:
          tags: [ 'perun_certs' ]
      vars:
        certbot_hostname: "{{ perun_ngui_hostname }}"
        certbot_prehook: perun_prehook.sh
        certbot_posthook: perun_posthook.sh

    - name: "create link to host key"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_rpc_hostname }}/privkey.pem"
        dest: "{{ perun_certificate_key_file }}"

    - name: "create link to host cert"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_rpc_hostname }}/cert.pem"
        dest: "{{ perun_certificate_file }}"

    - name: "create link to host chain"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_rpc_hostname }}/chain.pem"
        dest: "{{ perun_certificate_chain_file }}"

    - name: "create link to host full chain"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_rpc_hostname }}/fullchain.pem"
        dest: "{{ perun_certificate_fullchain_file }}"

    - name: "create link to ngui key"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_ngui_hostname }}/privkey.pem"
        dest: "{{ perun_certs_dir }}/nguikey.pem"

    - name: "create link to ngui cert"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_ngui_hostname }}/cert.pem"
        dest: "{{ perun_certs_dir }}/nguicert.pem"

    - name: "create link to ngui chain"
      file:
        state: link
        src: "/etc/letsencrypt/live/{{ perun_ngui_hostname }}/chain.pem"
        dest: "{{ perun_certs_dir }}/nguichain.pem"

- name: "use issued certificates"
  when: not perun_use_certbot_certificates
  block:
    - name: "set host key"
      copy:
        src: "{{ perun_instance_hostname }}/hostkey.pem"
        dest: "{{ perun_certificate_key_file }}"
        owner: root
        group: ssl-cert
        mode: 0640
      notify:
        - "restart perun_apache"
        - "restart portainer"
        - "restart ldap"
        - "restart postgres"

    - name: "set host certificate"
      copy:
        src: "{{ perun_instance_hostname }}/hostcert.pem"
        dest: "{{ perun_certificate_file}}"
        owner: root
        group: root
        mode: 0644
      register: certfile
      notify:
        - "restart perun_apache"
        - "restart ldap"
        - "restart postgres"

    - name: "set host chain"
      copy:
        src: "{{ perun_instance_hostname }}/hostchain.pem"
        dest: "{{ perun_certificate_chain_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - "restart perun_apache"
        - "restart ldap"
        - "restart postgres"

    - name: "assemble full chain (for portainer)"
      shell:
        chdir: "{{ perun_certs_dir }}"
        cmd: "cat {{ perun_certificate_file}} {{ perun_certificate_chain_file }} >{{ perun_certificate_fullchain_file }}"
      when: certfile.changed
      notify: "restart portainer"

    - name: "set NGUI key"
      copy:
        src: "{{ perun_instance_hostname }}/nguikey.pem"
        dest: "{{ perun_certs_dir }}/nguikey.pem"
        owner: root
        group: ssl-cert
        mode: 0640
      notify:
        - "restart perun_apache"

    - name: "set NGUI certificate"
      copy:
        src: "{{ perun_instance_hostname }}/nguicert.pem"
        dest: "{{ perun_certs_dir }}/nguicert.pem"
        owner: root
        group: root
        mode: 0644
      notify:
        - "restart perun_apache"

    - name: "set NGUI chain"
      copy:
        src: "{{ perun_instance_hostname }}/nguichain.pem"
        dest: "{{ perun_certs_dir }}/nguichain.pem"
        owner: root
        group: root
        mode: 0644
      notify:
        - "restart perun_apache"
